project_id = "rose-realstate-local"

[functions.send-property-email]
verify_jwt = false

[functions.auth-email-hook]
verify_jwt = false

[functions.send-reset-password-email]

[functions.api-ai-status]
enabled = true
verify_jwt = true
import_map = "./functions/api-ai-status/deno.json"
